# Generated by Django 4.1.3 on 2022-12-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profileimg_alter_profile_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timeline',
            field=models.ImageField(blank=True, default='defaults/timeline1.png', null=True, upload_to='timeline_images', verbose_name='Timeline Picture'),
        ),
    ]
