# Generated by Django 4.1.3 on 2022-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timeline',
            field=models.ImageField(blank=True, default='defaults/pythonweb-timeline.png', null=True, upload_to='timeline_images', verbose_name='Timeline Picture'),
        ),
    ]
